// Recipe List
export const FETCH_RECIPE_LIST = 'FETCH_RECIPE_LIST';
export const FETCH_RECIPE_LIST_SUCCESS = 'FETCH_RECIPE_LIST_SUCCESS';

// Detailed Recipe 
export const FETCH_DETAILED_RECIPE = 'FETCH_DETAILED_RECIPE';
export const FETCH_DETAILED_RECIPE_SUCCESS = 'FETCH_DETAILED_RECIPE_SUCESS';

// loading
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// favourites
export const ADD_FAVOURITES = 'ADD_RECIPE_TO_FAVOURITES';
export const ADD_FAVOURITES_SUCCESS = 'ADD_RECIPE_TO_FAVOURITES_SUCCESS';
export const FETCH_FAVOURITES = 'FETCH_FAVOURITES';
export const FETCH_FAVOURITES_SUCCESS = 'FETCH_FAVOURITES_SUCCESS';
export const DE_AUTH_FAVOURITES = 'DE_AUTH_FAVOURITES';
export const DELETE_FAVOURITES = 'DELETE_FAVOURITES';
export const DELETE_FAVOURITES_SUCCESS = 'DELETE_FAVOURITES_SUCCESS';

// Authentication
export const SIGN_IN_USER = 'SIGN_IN_USER'; 
export const AUTH_USER = 'AUTH_USER';
export const DE_AUTH_USER = 'DE_AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_DATA = 'FETCH_DATA';

//  User
export const GET_USER = 'GET_USER';

// Compare
export const ADD_COMPARE_RECIPES = 'ADD_COMPARE_RECIPES';
export const REMOVE_COMPARE = 'REMOVE_COMPARE';