// Recipe List
export const FETCH_RECIPE_LIST = 'FETCH_RECIPE_LIST';
export const FETCH_RECIPE_LIST_SUCCESS = 'FETCH_RECIPE_LIST_SUCCESS';

// Detailed Recipe 
export const FETCH_DETAILED_RECIPE = 'FETCH_DETAILED_RECIPE';
export const FETCH_DETAILED_RECIPE_SUCCESS = 'FETCH_DETAILED_RECIPE_SUCESS';
